### ISSUE TITLE
Link Inside Sortable Element

### ISSUE THREAD

**Issue by MatrixMediaSrl** [gardiner/draganddrop#13]
Hello,
congratulations for the script, very useful !!!

unfortunately I have found this problem, I have not found a way to insert a link, inside one or more sortable elements.

Tips?
regards

**Comment by gardiner** [comment]
Hi, what exactly does not work? I suspect that the mouse event handling collides with the default anchor-mouse-handling, but without more details I can only guess...

Cheers, Ole.

**Comment by MatrixMediaSrl** [comment]
Hi,
Thanks for the reply.

I created a simple sortable list:

```
<ul>
<li>Hello click <a href="#url1">here</a></li>
<li>Hello click <a href="#url2">here</a></li>
<li>Hello click <a href="#url3">here</a></li>
<li>Hello click <a href="#url4">here</a></li>
</ul>
```

when I click on the link, the "sortable" function is "activated" and the link is unusable.

If I remember correctly, jqueryUI, to solve this problem, used the option: `helper : clone`

Thanks for the attention
Regards

**Comment by gardiner** [comment]
Hi, draganddrop has an option `handle`  which accepts a selector specifying what elements should react to drag and drop events, e.g. `handle: '.sorthandle'`. You could then modify your markup like this:

`<li><span class="sorthandle">Hello click</span> <a href="#url1">here</a></li>`

I haven't tried it yet, though, please let me know if you need further help. Cheers.

**Comment by MatrixMediaSrl** [comment]
sorry, sorry, sorry ...
... I have not seen this option !!!

I set the option and now everything works perfectly !!!

Thanks so much!!!
Best Regards!!!

**Comment by gardiner** [comment]
Great :) Cheers!
